a:
	g++ A.cpp -o a.exe
	a.exe
b:
	g++ B.cpp -o b.exe 
	b.exe
c:
	g++ C.cpp -o c.exe 
	c.exe
d:
	g++ D.cpp -o d.exe
	d.exe
e:
	g++ E.cpp -o e.exe
	e.exe
f:
	g++ F.cpp -o f.exe
	f.exe
g:
	g++ G.cpp -o g.exe
	g.exe
j:
	g++ J.cpp -o j.exe
	j.exe
