a:
	g++ A.cpp -o a.out
	./a.out
b:
	g++ B.cpp -o b.out 
	./b.out
b2: 
	g++ B2.cpp -o b2.out
	./b2.out
c:
	g++ C.cpp -o c.out 
	./c.out
d:
	g++ D.cpp -o d.out
	./d.out
e:
	g++ E.cpp -o e.out
	./e.out
f:
	g++ F.cpp -o f.out
	./f.out
